namespace JC_ICR
{
    partial class Audio
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            OpenWire.Proxy.MultiSinkPin multiSinkPin2 = new OpenWire.Proxy.MultiSinkPin();
            OpenWire.Proxy.SourcePin sourcePin4 = new OpenWire.Proxy.SourcePin();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Audio));
            Mitov.AudioLab.AudioPlayerSegment audioPlayerSegment2 = new Mitov.AudioLab.AudioPlayerSegment();
            OpenWire.Proxy.StatePin statePin4 = new OpenWire.Proxy.StatePin();
            OpenWire.Proxy.SourcePin sourcePin5 = new OpenWire.Proxy.SourcePin();
            Mitov.AudioLab.AudioOutDevice audioOutDevice2 = new Mitov.AudioLab.AudioOutDevice();
            OpenWire.Proxy.SinkPin sinkPin4 = new OpenWire.Proxy.SinkPin();
            Mitov.BasicLab.MasterPumping masterPumping2 = new Mitov.BasicLab.MasterPumping();
            Mitov.PlotLab.ScopeChannel scopeChannel3 = new Mitov.PlotLab.ScopeChannel();
            Mitov.PlotLab.ScopePoints scopePoints3 = new Mitov.PlotLab.ScopePoints();
            Vcl.VclPen vclPen8 = new Vcl.VclPen();
            Mitov.PlotLab.ScopeChannel scopeChannel4 = new Mitov.PlotLab.ScopeChannel();
            Mitov.PlotLab.ScopePoints scopePoints4 = new Mitov.PlotLab.ScopePoints();
            Vcl.VclPen vclPen9 = new Vcl.VclPen();
            Mitov.PlotLab.ScopeDataView scopeDataView2 = new Mitov.PlotLab.ScopeDataView();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground6 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings6 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen10 = new Vcl.VclPen();
            Mitov.PlotLab.DataChartHighlighting dataChartHighlighting2 = new Mitov.PlotLab.DataChartHighlighting();
            Mitov.PlotLab.ChannelItemHighlighting channelItemHighlighting3 = new Mitov.PlotLab.ChannelItemHighlighting();
            Mitov.PlotLab.ChannelItemHighlighting channelItemHighlighting4 = new Mitov.PlotLab.ChannelItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting7 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting8 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting9 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting10 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting11 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.ChannelMouseHitPoint channelMouseHitPoint2 = new Mitov.PlotLab.ChannelMouseHitPoint();
            Mitov.BasicLab.OptionalLabel optionalLabel2 = new Mitov.BasicLab.OptionalLabel();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting12 = new Mitov.PlotLab.DisplayItemHighlighting();
            OpenWire.Proxy.PinList pinList4 = new OpenWire.Proxy.PinList();
            Mitov.PlotLab.ScopeLegendView scopeLegendView2 = new Mitov.PlotLab.ScopeLegendView();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground7 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.LegendViewButtonSettings legendViewButtonSettings2 = new Mitov.PlotLab.LegendViewButtonSettings();
            Mitov.PlotLab.LegendGroup legendGroup9 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel9 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup10 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel10 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup11 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel11 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup12 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel12 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup13 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel13 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup14 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel14 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup15 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel15 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.DisplayViewSize displayViewSize5 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.LegendGroup legendGroup16 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel16 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.DisplayTitle displayTitle2 = new Mitov.PlotLab.DisplayTitle();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground8 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.DisplayViewSize displayViewSize6 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayToolBar displayToolBar2 = new Mitov.PlotLab.DisplayToolBar();
            Mitov.PlotLab.DisplayToolBarButtons displayToolBarButtons2 = new Mitov.PlotLab.DisplayToolBarButtons();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton23 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage23 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton24 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage24 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton25 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage25 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton26 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage26 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton27 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage27 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton28 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage28 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton29 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage29 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize4 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton30 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage30 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton31 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage31 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton32 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage32 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton33 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage33 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton34 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage34 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton35 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage35 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton36 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage36 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ToolBarPosition toolBarPosition2 = new Mitov.PlotLab.ToolBarPosition();
            Mitov.PlotLab.DisplayTrails displayTrails2 = new Mitov.PlotLab.DisplayTrails();
            Mitov.PlotLab.ScopeXAxis scopeXAxis2 = new Mitov.PlotLab.ScopeXAxis();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel3 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground9 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings3 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings3 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings3 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings7 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen11 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings8 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen12 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat3 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks3 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart3 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue3 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange7 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue13 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue14 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue5 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.ScopeMaxSample scopeMaxSample2 = new Mitov.PlotLab.ScopeMaxSample();
            Mitov.PlotLab.AxisValue axisValue3 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange8 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue15 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue16 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue6 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks3 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar3 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons3 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize5 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton37 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage37 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton38 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage38 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton39 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage39 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton40 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage40 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ScopeXAxisUnitScale scopeXAxisUnitScale2 = new Mitov.PlotLab.ScopeXAxisUnitScale();
            Mitov.PlotLab.DisplayViewSize displayViewSize7 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom3 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange9 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue17 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue18 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin5 = new OpenWire.Proxy.StatePin();
            OpenWire.Proxy.PinList pinList5 = new OpenWire.Proxy.PinList();
            Mitov.PlotLab.ScopeYAxis scopeYAxis2 = new Mitov.PlotLab.ScopeYAxis();
            Mitov.PlotLab.ScopeAutoScaling scopeAutoScaling2 = new Mitov.PlotLab.ScopeAutoScaling();
            Mitov.PlotLab.ScopeAutoScalingSpace scopeAutoScalingSpace3 = new Mitov.PlotLab.ScopeAutoScalingSpace();
            Mitov.PlotLab.ScopeAutoScalingSpace scopeAutoScalingSpace4 = new Mitov.PlotLab.ScopeAutoScalingSpace();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel4 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground10 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings4 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings4 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings4 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings9 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen13 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings10 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen14 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat4 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks4 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart4 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue4 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange10 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue19 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue20 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue7 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.AxisValue axisValue4 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange11 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue21 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue22 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue8 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks4 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar4 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons4 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize6 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton41 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage41 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton42 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage42 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton43 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage43 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton44 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage44 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayViewSize displayViewSize8 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom4 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange12 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue23 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue24 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin6 = new OpenWire.Proxy.StatePin();
            Mitov.PlotLab.DisplayZoom displayZoom2 = new Mitov.PlotLab.DisplayZoom();
            OpenWire.Proxy.SinkPin sinkPin5 = new OpenWire.Proxy.SinkPin();
            OpenWire.Proxy.SourcePin sourcePin6 = new OpenWire.Proxy.SourcePin();
            OpenWire.Proxy.SinkPin sinkPin6 = new OpenWire.Proxy.SinkPin();
            OpenWire.Proxy.PinList pinList6 = new OpenWire.Proxy.PinList();
            this.wavePlayer1 = new Mitov.AudioLab.WavePlayer(this.components);
            this.audioOut1 = new Mitov.AudioLab.AudioOut(this.components);
            this.scope1 = new Mitov.PlotLab.Scope(this.components);
            this.rmsMeter1 = new Mitov.SignalLab.RMSMeter(this.components);
            this.audioToReal1 = new Mitov.AudioLab.AudioToReal(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.wavePlayer1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.audioOut1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.scope1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.rmsMeter1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.audioToReal1)).BeginInit();
            this.SuspendLayout();
            // 
            // wavePlayer1
            // 
            this.wavePlayer1.ClockPin = multiSinkPin2;
            this.wavePlayer1.FileName = "C:\\Users\\vaka\\Desktop\\1kHz_44100Hz_16bit_30sec.wav";
            sourcePin4.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("sourcePin4.ConnectionData")));
            this.wavePlayer1.OutputPin = sourcePin4;
            audioPlayerSegment2.StartSample = ((long)(0));
            audioPlayerSegment2.StopSample = ((long)(100));
            this.wavePlayer1.PlaySegment = audioPlayerSegment2;
            this.wavePlayer1.ProgressPin = statePin4;
            this.wavePlayer1.PumpPriority = ((uint)(0u));
            // 
            // audioOut1
            // 
            this.audioOut1.ClockOutputPin = sourcePin5;
            this.audioOut1.Device = audioOutDevice2;
            sinkPin4.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("sinkPin4.ConnectionData")));
            this.audioOut1.InputPin = sinkPin4;
            masterPumping2.Priority = ((uint)(0u));
            this.audioOut1.MasterPumping = masterPumping2;
            this.audioOut1.PrefillInterval = ((uint)(300u));
            // 
            // scope1
            // 
            this.scope1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeChannel3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeChannel3.MouseCursor = System.Windows.Forms.Cursors.Default;
            scopeChannel3.Name = "Channel0";
            scopePoints3.Brush = new Vcl.VclBrush(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), 0);
            vclPen8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen8.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen8.InternalData")));
            scopePoints3.Pen = vclPen8;
            scopePoints3.Size = ((uint)(3u));
            scopeChannel3.Points = scopePoints3;
            scopeChannel3.SizeLimit = ((uint)(0u));
            scopeChannel3.XAxisIndex = 0;
            scopeChannel3.YAxisIndex = 0;
            scopeChannel4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            scopeChannel4.MouseCursor = System.Windows.Forms.Cursors.Default;
            scopeChannel4.Name = "Channel1";
            scopePoints4.Brush = new Vcl.VclBrush(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), 0);
            vclPen9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen9.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen9.InternalData")));
            scopePoints4.Pen = vclPen9;
            scopePoints4.Size = ((uint)(3u));
            scopeChannel4.Points = scopePoints4;
            scopeChannel4.SizeLimit = ((uint)(0u));
            scopeChannel4.XAxisIndex = 0;
            scopeChannel4.YAxisIndex = 0;
            this.scope1.Channels.AddRange(new Mitov.PlotLab.ScopeChannel[] {
            scopeChannel3,
            scopeChannel4});
            displayViewBackground6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeDataView2.Background = displayViewBackground6;
            vclPen10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            vclPen10.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen10.InternalData")));
            displayGridLineSettings6.Pen = vclPen10;
            scopeDataView2.Border = displayGridLineSettings6;
            this.scope1.DataView = scopeDataView2;
            channelItemHighlighting3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting2.ChannelLinks = channelItemHighlighting3;
            channelItemHighlighting4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting2.Channels = channelItemHighlighting4;
            displayItemHighlighting7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting2.CursorLinks = displayItemHighlighting7;
            displayItemHighlighting8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting2.Cursors = displayItemHighlighting8;
            displayItemHighlighting9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting2.Ellipses = displayItemHighlighting9;
            displayItemHighlighting10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting2.Labels = displayItemHighlighting10;
            displayItemHighlighting11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting2.Markers = displayItemHighlighting11;
            channelMouseHitPoint2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            optionalLabel2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            channelMouseHitPoint2.PointLabel = optionalLabel2;
            dataChartHighlighting2.MouseHitPoint = channelMouseHitPoint2;
            displayItemHighlighting12.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting2.Zones = displayItemHighlighting12;
            this.scope1.Highlighting = dataChartHighlighting2;
            pinList4.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("pinList4.ConnectionData")));
            this.scope1.InputPins = pinList4;
            this.scope1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scope1.InternalData")));
            displayViewBackground7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeLegendView2.Background = displayViewBackground7;
            legendViewButtonSettings2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.Cursor = System.Windows.Forms.Cursors.Default;
            legendViewButtonSettings2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeLegendView2.Buttons = legendViewButtonSettings2;
            displayLabel9.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup9.Caption = displayLabel9;
            legendGroup9.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.ChannelLinks = legendGroup9;
            displayLabel10.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup10.Caption = displayLabel10;
            legendGroup10.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Channels = legendGroup10;
            displayLabel11.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup11.Caption = displayLabel11;
            legendGroup11.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.CursorLinks = legendGroup11;
            displayLabel12.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup12.Caption = displayLabel12;
            legendGroup12.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Cursors = legendGroup12;
            displayLabel13.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup13.Caption = displayLabel13;
            legendGroup13.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Ellipses = legendGroup13;
            scopeLegendView2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            scopeLegendView2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeLegendView2.InternalData")));
            displayLabel14.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup14.Caption = displayLabel14;
            legendGroup14.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Labels = legendGroup14;
            displayLabel15.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup15.Caption = displayLabel15;
            legendGroup15.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.MarkerGroups = legendGroup15;
            displayViewSize5.Size = ((uint)(100u));
            scopeLegendView2.ViewSize = displayViewSize5;
            displayLabel16.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup16.Caption = displayLabel16;
            legendGroup16.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Zones = legendGroup16;
            this.scope1.Legend = scopeLegendView2;
            this.scope1.Location = new System.Drawing.Point(73, 49);
            this.scope1.Name = "scope1";
            this.scope1.RefreshInterval = ((uint)(100u));
            this.scope1.Size = new System.Drawing.Size(501, 258);
            this.scope1.SizeLimit = ((uint)(0u));
            this.scope1.TabIndex = 0;
            this.scope1.Text = "scope1";
            displayViewBackground8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayTitle2.Background = displayViewBackground8;
            displayTitle2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 27, 1);
            displayTitle2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("displayTitle2.InternalData")));
            displayTitle2.Text = "Scope";
            displayViewSize6.Size = ((uint)(100u));
            displayTitle2.ViewSize = displayViewSize6;
            this.scope1.Title = displayTitle2;
            displayToolBar2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar2.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayToolBarButton23.Image = displayToolBarButtonImage23;
            displayToolBarButtons2.Copy = displayToolBarButton23;
            displayToolBarButton24.Image = displayToolBarButtonImage24;
            displayToolBarButtons2.Hold = displayToolBarButton24;
            displayToolBarButton25.Image = displayToolBarButtonImage25;
            displayToolBarButtons2.PanMode = displayToolBarButton25;
            displayToolBarButton26.Image = displayToolBarButtonImage26;
            displayToolBarButtons2.Print = displayToolBarButton26;
            displayToolBarButton27.Image = displayToolBarButtonImage27;
            displayToolBarButtons2.Run = displayToolBarButton27;
            displayToolBarButton28.Image = displayToolBarButtonImage28;
            displayToolBarButtons2.Save = displayToolBarButton28;
            displayToolBarButton29.Image = displayToolBarButtonImage29;
            displayToolBarButtons2.Setup = displayToolBarButton29;
            displayToolBarButtons2.Size = toolBarButtonSize4;
            displayToolBarButton30.Image = displayToolBarButtonImage30;
            displayToolBarButtons2.XYZoomOn = displayToolBarButton30;
            displayToolBarButton31.Image = displayToolBarButtonImage31;
            displayToolBarButtons2.ZoomIn = displayToolBarButton31;
            displayToolBarButton32.Image = displayToolBarButtonImage32;
            displayToolBarButtons2.ZoomMode = displayToolBarButton32;
            displayToolBarButton33.Image = displayToolBarButtonImage33;
            displayToolBarButtons2.ZoomNext = displayToolBarButton33;
            displayToolBarButton34.Image = displayToolBarButtonImage34;
            displayToolBarButtons2.ZoomOff = displayToolBarButton34;
            displayToolBarButton35.Image = displayToolBarButtonImage35;
            displayToolBarButtons2.ZoomOut = displayToolBarButton35;
            displayToolBarButton36.Image = displayToolBarButtonImage36;
            displayToolBarButtons2.ZoomPrevious = displayToolBarButton36;
            displayToolBar2.Buttons = displayToolBarButtons2;
            displayToolBar2.Cursor = System.Windows.Forms.Cursors.Default;
            displayToolBar2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar2.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar2.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar2.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar2.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar2.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            toolBarPosition2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("toolBarPosition2.InternalData")));
            displayToolBar2.Position = toolBarPosition2;
            this.scope1.ToolBar = displayToolBar2;
            displayTrails2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            displayTrails2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            displayTrails2.Width = ((uint)(1u));
            this.scope1.Trails = displayTrails2;
            displayTitleLabel3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            scopeXAxis2.AxisLabel = displayTitleLabel3;
            displayViewBackground9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis2.Background = displayViewBackground9;
            viewButtonSettings3.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings3.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings3.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings3.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings3.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeXAxis2.Button = viewButtonSettings3;
            scopeXAxis2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            scopeXAxis2.CursorSettings = displayAxisCursorSettings3;
            vclPen11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            vclPen11.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen11.InternalData")));
            displayGridLineSettings7.Pen = vclPen11;
            displayGridDirectionalLinesSettings3.Lines = displayGridLineSettings7;
            vclPen12.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            vclPen12.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen12.InternalData")));
            displayGridLineSettings8.Pen = vclPen12;
            displayGridDirectionalLinesSettings3.ZeroLine = displayGridLineSettings8;
            scopeXAxis2.DataView = displayGridDirectionalLinesSettings3;
            scopeXAxis2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            axisFormat3.Precision = 3;
            scopeXAxis2.Format = axisFormat3;
            scopeXAxis2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeXAxis2.InternalData")));
            ticksStart3.StartFrom = 0D;
            majorTicks3.StartFrom = ticksStart3;
            majorTicks3.Step = 10D;
            scopeXAxis2.MajorTicks = majorTicks3;
            maxAxisValue3.DataValue = 1024D;
            displayOptionalValue13.Enabled = false;
            displayOptionalValue13.Value = 1000D;
            displayValueRange7.High = displayOptionalValue13;
            displayOptionalValue14.Enabled = false;
            displayOptionalValue14.Value = -1000D;
            displayValueRange7.Low = displayOptionalValue14;
            maxAxisValue3.Range = displayValueRange7;
            basicAxisValue5.Value = 1024D;
            maxAxisValue3.Tick = basicAxisValue5;
            maxAxisValue3.Value = 1024D;
            scopeXAxis2.Max = maxAxisValue3;
            scopeMaxSample2.Value = ((uint)(1024u));
            scopeXAxis2.MaxSample = scopeMaxSample2;
            axisValue3.DataValue = 0D;
            displayOptionalValue15.Enabled = false;
            displayOptionalValue15.Value = 1000D;
            displayValueRange8.High = displayOptionalValue15;
            displayOptionalValue16.Enabled = false;
            displayOptionalValue16.Value = -1000D;
            displayValueRange8.Low = displayOptionalValue16;
            axisValue3.Range = displayValueRange8;
            basicAxisValue6.Value = 0D;
            axisValue3.Tick = basicAxisValue6;
            axisValue3.Value = 0D;
            scopeXAxis2.Min = axisValue3;
            scopeXAxis2.MinorTicks = minorTicks3;
            axisToolBar3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar3.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons3.Size = toolBarButtonSize5;
            displayToolBarButton37.Image = displayToolBarButtonImage37;
            axisToolBarButtons3.ZoomIn = displayToolBarButton37;
            displayToolBarButton38.Image = displayToolBarButtonImage38;
            axisToolBarButtons3.ZoomOff = displayToolBarButton38;
            displayToolBarButton39.Image = displayToolBarButtonImage39;
            axisToolBarButtons3.ZoomOneDir = displayToolBarButton39;
            displayToolBarButton40.Image = displayToolBarButtonImage40;
            axisToolBarButtons3.ZoomOut = displayToolBarButton40;
            axisToolBar3.Buttons = axisToolBarButtons3;
            axisToolBar3.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar3.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar3.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar3.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar3.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar3.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar3.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeXAxis2.ToolBar = axisToolBar3;
            scopeXAxis2.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis2.UnitScale = scopeXAxisUnitScale2;
            displayViewSize7.Size = ((uint)(100u));
            scopeXAxis2.ViewSize = displayViewSize7;
            displayOptionalValue17.Enabled = false;
            displayOptionalValue17.Value = 100000000D;
            displayValueRange9.High = displayOptionalValue17;
            displayOptionalValue18.Enabled = true;
            displayOptionalValue18.Value = 1E-07D;
            displayValueRange9.Low = displayOptionalValue18;
            displayAxisZoom3.Range = displayValueRange9;
            scopeXAxis2.Zooming = displayAxisZoom3;
            scopeXAxis2.ZoomPin = statePin5;
            this.scope1.XAxis = scopeXAxis2;
            this.scope1.XInputPins = pinList5;
            scopeAutoScaling2.MaxHistory = ((uint)(20u));
            scopeAutoScalingSpace3.Space = ((uint)(20u));
            scopeAutoScalingSpace3.Threshold = ((uint)(10u));
            scopeAutoScaling2.SpaceAbove = scopeAutoScalingSpace3;
            scopeAutoScalingSpace4.Space = ((uint)(20u));
            scopeAutoScalingSpace4.Threshold = ((uint)(10u));
            scopeAutoScaling2.SpaceBelow = scopeAutoScalingSpace4;
            scopeYAxis2.AutoScaling = scopeAutoScaling2;
            displayTitleLabel4.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            displayTitleLabel4.Text = "Y Axis";
            scopeYAxis2.AxisLabel = displayTitleLabel4;
            displayViewBackground10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeYAxis2.Background = displayViewBackground10;
            viewButtonSettings4.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings4.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings4.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings4.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings4.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeYAxis2.Button = viewButtonSettings4;
            scopeYAxis2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            scopeYAxis2.CursorSettings = displayAxisCursorSettings4;
            vclPen13.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            vclPen13.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen13.InternalData")));
            displayGridLineSettings9.Pen = vclPen13;
            displayGridDirectionalLinesSettings4.Lines = displayGridLineSettings9;
            vclPen14.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            vclPen14.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen14.InternalData")));
            displayGridLineSettings10.Pen = vclPen14;
            displayGridDirectionalLinesSettings4.ZeroLine = displayGridLineSettings10;
            scopeYAxis2.DataView = displayGridDirectionalLinesSettings4;
            scopeYAxis2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            axisFormat4.Precision = 3;
            scopeYAxis2.Format = axisFormat4;
            scopeYAxis2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeYAxis2.InternalData")));
            ticksStart4.StartFrom = 0D;
            majorTicks4.StartFrom = ticksStart4;
            majorTicks4.Step = 10D;
            scopeYAxis2.MajorTicks = majorTicks4;
            maxAxisValue4.DataValue = 1000D;
            displayOptionalValue19.Enabled = false;
            displayOptionalValue19.Value = 1000D;
            displayValueRange10.High = displayOptionalValue19;
            displayOptionalValue20.Enabled = false;
            displayOptionalValue20.Value = -1000D;
            displayValueRange10.Low = displayOptionalValue20;
            maxAxisValue4.Range = displayValueRange10;
            basicAxisValue7.Value = 0D;
            maxAxisValue4.Tick = basicAxisValue7;
            maxAxisValue4.Value = 1000D;
            scopeYAxis2.Max = maxAxisValue4;
            axisValue4.DataValue = -1000D;
            displayOptionalValue21.Enabled = false;
            displayOptionalValue21.Value = 1000D;
            displayValueRange11.High = displayOptionalValue21;
            displayOptionalValue22.Enabled = false;
            displayOptionalValue22.Value = -1000D;
            displayValueRange11.Low = displayOptionalValue22;
            axisValue4.Range = displayValueRange11;
            basicAxisValue8.Value = 0D;
            axisValue4.Tick = basicAxisValue8;
            axisValue4.Value = -1000D;
            scopeYAxis2.Min = axisValue4;
            scopeYAxis2.MinorTicks = minorTicks4;
            axisToolBar4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar4.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons4.Size = toolBarButtonSize6;
            displayToolBarButton41.Image = displayToolBarButtonImage41;
            axisToolBarButtons4.ZoomIn = displayToolBarButton41;
            displayToolBarButton42.Image = displayToolBarButtonImage42;
            axisToolBarButtons4.ZoomOff = displayToolBarButton42;
            displayToolBarButton43.Image = displayToolBarButtonImage43;
            axisToolBarButtons4.ZoomOneDir = displayToolBarButton43;
            displayToolBarButton44.Image = displayToolBarButtonImage44;
            axisToolBarButtons4.ZoomOut = displayToolBarButton44;
            axisToolBar4.Buttons = axisToolBarButtons4;
            axisToolBar4.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar4.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar4.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar4.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar4.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar4.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar4.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeYAxis2.ToolBar = axisToolBar4;
            scopeYAxis2.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayViewSize8.Size = ((uint)(100u));
            scopeYAxis2.ViewSize = displayViewSize8;
            displayOptionalValue23.Enabled = false;
            displayOptionalValue23.Value = 100000000D;
            displayValueRange12.High = displayOptionalValue23;
            displayOptionalValue24.Enabled = true;
            displayOptionalValue24.Value = 1E-07D;
            displayValueRange12.Low = displayOptionalValue24;
            displayAxisZoom4.Range = displayValueRange12;
            scopeYAxis2.Zooming = displayAxisZoom4;
            scopeYAxis2.ZoomPin = statePin6;
            this.scope1.YAxis = scopeYAxis2;
            displayZoom2.SelectionColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.scope1.Zooming = displayZoom2;
            // 
            // rmsMeter1
            // 
            sinkPin5.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("sinkPin5.ConnectionData")));
            this.rmsMeter1.InputPin = sinkPin5;
            this.rmsMeter1.OutputPin = sourcePin6;
            // 
            // audioToReal1
            // 
            sinkPin6.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("sinkPin6.ConnectionData")));
            this.audioToReal1.InputPin = sinkPin6;
            pinList6.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("pinList6.ConnectionData")));
            this.audioToReal1.OutputPins = pinList6;
            // 
            // Audio
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(614, 357);
            this.Controls.Add(this.scope1);
            this.Name = "Audio";
            this.Text = "Audio";
            ((System.ComponentModel.ISupportInitialize)(this.wavePlayer1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.audioOut1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.scope1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.rmsMeter1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.audioToReal1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Mitov.AudioLab.WavePlayer wavePlayer1;
        private Mitov.AudioLab.AudioOut audioOut1;
        private Mitov.PlotLab.Scope scope1;
        private Mitov.SignalLab.RMSMeter rmsMeter1;
        private Mitov.AudioLab.AudioToReal audioToReal1;
    }
}